---
title: "fsl_BIANCA"
author: "Niklas Wulms"
date: "5/11/2020"
output: html_document
---

```{r setup, include=FALSE}
library(stringr)
library(doParallel)
library(foreach)
library(tidyr)
library(dplyr)

source("fsl_flirt.R")
source("fsl_bet.R")
source("fsl_BIANCA.r")
source("../../functions/general.R")

knitr::opts_chunk$set(echo = TRUE)

working_dir <- "/mnt/Vierer/BIDS/derivatives_temp/FSL/"
knitr::opts_knit$set(root.dir = working_dir)
setwd(working_dir)
```


```{r}
nii_files <- tibble(
  # raw input and first preprocs
  T1w = list.files("/mnt/Vierer/BIDS/derivatives_temp/FSL/fsl_flirt_pipeline/",
                     "T1_biascorr_brain_T2_space_6", recursive = TRUE, full.names = TRUE),
  FLAIR = list.files("/mnt/Vierer/BIDS/derivatives_temp/FSL/fsl_flirt_pipeline/",
                     "FLAIR_T1_space_brain_T2_space_6", recursive = TRUE, full.names = TRUE),
  mat_file = list.files("/mnt/Vierer/BIDS/derivatives_temp/FSL/fsl_flirt_pipeline/", 
                        "T2_0.5_biascorr_T1_space_6_FLAIR_to_MNI", recursive = TRUE, full.names = TRUE))             


dir.create("/mnt/Vierer/BIDS/derivatives_temp/FSL/fsl_bianca_pipeline/")

bianca_file <- "/mnt/Vierer/BIDS/derivatives_temp/FSL/fsl_bianca_pipeline/list_of_files.txt"


nii_files %>%
  write.table(file=bianca_file, 
              quote=FALSE, sep='\t', col.names = FALSE, row.names = FALSE)


```

```{r}
model121 <- "/home/niklas/Owncloud/wulms/BiDirect_Neuroimaging/BIANCA_classifier/output_classifier_121"
model201 <- "/home/niklas/Owncloud/wulms/BiDirect_Neuroimaging/BIANCA_classifier/output_classifier_201"
```

```{r}
application_bianca_classifiers(trained_models = c(model121), 
                               test_sets = bianca_file,
                               prefix = "model_121")
```

```{r}
bianca_masks <- list.files(path = "/mnt/Vierer/BIDS/derivatives_temp/FSL/fsl_bianca_pipeline/", "_mask.nii.gz",
           recursive = TRUE, 
           full.names = TRUE)
```




```{r}

masks <- tibble(bianca_masks = list.files(path = "/mnt/Vierer/BIDS/derivatives_temp/FSL/fsl_bianca_pipeline/", 
                                          "_mask.nii.gz",
                                          recursive = TRUE, 
                                          full.names = TRUE),
                threshold = 0.8,
                bianca_output = str_replace(bianca_masks, ".nii.gz", "_volume.txt"))

bianca_cluster_info(lesionmask = masks$bianca_masks, 
                    threshold = masks$threshold,
                    output_name = masks$bianca_output)

```

```{r}

```



```{r}
setwd(working_dir)
masks2 <- masks %>%
  mutate(exists = file.exists(bianca_output),
         wmh_number = lapply(bianca_output, volume_extractor, "wmh_number") %>% unlist(),
         wmh_volume = lapply(bianca_output, volume_extractor, "total_wmh_volume") %>% unlist()
         )
```


```{r}
masks3 <- masks2 %>%
  mutate(subject = str_extract(bianca_output, "sub-[:digit:]{5}"),
         session = str_extract(bianca_output, "ses-s[:digit:]{1}")) %>%
  select(subject, session, wmh_number, wmh_volume) 

masks3 %>%
  write.csv(file = "wmh_bianca_thresh08.csv", row.names = FALSE)
```

```{r}
loo_bianca <- readRDS("/home/niklas/Owncloud/wulms/BD_variablen/permutations_BIANCA/wml121_bianca_masks.rds") %>%
  filter(thresh == 0.8) %>%
  mutate(session = str_replace(session, "ses-S", "ses-s")) %>%
  filter(str_detect(input, "121")) %>%
  select(subject, session, total_volume) %>%
  left_join(masks3) %>%
  mutate(wmh_volume = as.numeric(wmh_volume),
         total_volume = as.numeric(total_volume))
```

## New stuff

```{r}
model121 <- "/home/niklas/Owncloud/wulms/BiDirect_Neuroimaging/BIANCA_classifier/output_classifier_121"
model201 <- "/home/niklas/Owncloud/wulms/BiDirect_Neuroimaging/BIANCA_classifier/output_classifier_201"
```

```{r}
# Deface pipeline

# 4320
T1 = list.files("/mnt/Vierer/BIDS/derivatives_temp/FSL/fsl_deface_pipeline/", "T1w_fsldeface_bet_0.5_FLAIR_space.nii", #27
                                 recursive = TRUE, full.names = TRUE)
FLAIR =  list.files("/mnt/Vierer/BIDS/derivatives_temp/FSL/fsl_deface_pipeline/", "FLAIR_T1w_space_fsldeface_bet_0.5_FLAIR_space.nii", #27
                                 recursive = TRUE, full.names = TRUE)
mat1 =  list.files("/mnt/Vierer/BIDS/derivatives_temp/FSL/fsl_anat_pipeline/", "FLAIR_bet_0.4_T1_space_6.mat",
                                 recursive = TRUE, full.names = TRUE)

model1 <- tibble(T1 = T1, 
                 FLAIR = FLAIR,
                 mat = mat)

# 4314
T1 = list.files("/mnt/Vierer/BIDS/derivatives_temp/FSL/fsl_deface_pipeline/", "T1w_fsldeface_bet_0.5_FLAIR_anat_space.nii", #26
                                 recursive = TRUE, full.names = TRUE)
FLAIR =  list.files("/mnt/Vierer/BIDS/derivatives_temp/FSL/fsl_deface_pipeline/", "FLAIR_T1w_space_fsldeface_bet_0.5_FLAIR_anat_space.nii", #26
                                 recursive = TRUE, full.names = TRUE)
mat2 =  list.files("/mnt/Vierer/BIDS/derivatives_temp/FSL/fsl_anat_pipeline/", "biascorr_bet_0.4_T1_space_6.mat",
                                 recursive = TRUE, full.names = TRUE)

model2 <- tibble(T1 = T1, 
                 FLAIR = FLAIR,
                 mat = mat2)


# Deface anat pipeline

#4320
T1 = list.files("/mnt/Vierer/BIDS/derivatives_temp/FSL/fsl_deface_anat_pipeline/", "T1_biascorr_bet_0.5_FLAIR_space.nii",
                                 recursive = TRUE, full.names = TRUE)
FLAIR =  list.files("/mnt/Vierer/BIDS/derivatives_temp/FSL/fsl_deface_anat_pipeline/", "FLAIR_T1w_space_biascorr_bet_0.5_FLAIR_space.nii", # 27
                                 recursive = TRUE, full.names = TRUE) 
mat3 =  list.files("/mnt/Vierer/BIDS/derivatives_temp/FSL/fsl_anat_pipeline/", "FLAIR_bet_0.4_T1_space_anat_6.mat",
                                 recursive = TRUE, full.names = TRUE)
  
model3 <- tibble(T1 = T1, 
                 FLAIR = FLAIR,
                 mat = mat3)

# 4320
T1 = list.files("/mnt/Vierer/BIDS/derivatives_temp/FSL/fsl_deface_anat_pipeline/", "T1_biascorr_bet_0.5_FLAIR_anat_space.nii", 
                                 recursive = TRUE, full.names = TRUE)
FLAIR =  list.files("/mnt/Vierer/BIDS/derivatives_temp/FSL/fsl_deface_anat_pipeline/", "FLAIR_T1w_space_biascorr_bet_0.5_FLAIR_anat_space.nii", # 26
                                 recursive = TRUE, full.names = TRUE)
mat4 =  list.files("/mnt/Vierer/BIDS/derivatives_temp/FSL/fsl_anat_pipeline/", "biascorr_bet_0.4_T1_space_anat_6.mat",
                                 recursive = TRUE, full.names = TRUE)

model4 <- tibble(T1 = T1, 
                 FLAIR = FLAIR,
                 mat = mat4)

```



```{r}
bianca_folder <- "/mnt/Vierer/BIDS/derivatives_temp/FSL/fsl_bianca_pipeline/"

bianca_file_1 <- paste0(bianca_folder, "deface.txt")
bianca_file_2 <- paste0(bianca_folder, "deface_anat.txt")
bianca_file_3 <- paste0(bianca_folder, "deface_bc.txt")
bianca_file_4 <- paste0(bianca_folder, "deface_bc_anat.txt")

path_to_folder(bianca_file_1)
path_to_folder(bianca_file_2)
path_to_folder(bianca_file_3)
path_to_folder(bianca_file_4)

write.table(x = model1, file=bianca_file_1, quote=FALSE, sep='\t', col.names = FALSE, row.names = FALSE)
write.table(x = model2, file=bianca_file_2, quote=FALSE, sep='\t', col.names = FALSE, row.names = FALSE)
write.table(x = model3, file=bianca_file_3, quote=FALSE, sep='\t', col.names = FALSE, row.names = FALSE)
write.table(x = model4, file=bianca_file_4, quote=FALSE, sep='\t', col.names = FALSE, row.names = FALSE)

```

## Artefacts

```{r eval=FALSE}
application_bianca_classifiers(trained_models = c(model121), 
                               test_sets = bianca_file_1,
                               prefix = "model_121_deface")

application_bianca_classifiers(trained_models = c(model121), 
                               test_sets = bianca_file_3,
                               prefix = "model_121_deface_bc")
```

# good prediction?

```{r}
application_bianca_classifiers(trained_models = c(model121), 
                               test_sets = bianca_file_2,
                               prefix = "model_121_deface_anat")

application_bianca_classifiers(trained_models = c(model121), 
                               test_sets = bianca_file_4,
                               prefix = "model_121_deface_bc_anat")
```

```{r}
pipeline1 <- list.files("/mnt/Vierer/BIDS/derivatives_temp/FSL/fsl_bianca_pipeline/model_121_deface_anat/", ".nii", recursive = TRUE, full.names = TRUE)
pipeline2 <- list.files("/mnt/Vierer/BIDS/derivatives_temp/FSL/fsl_bianca_pipeline/model_121_deface_bc_anat/", ".nii", recursive = TRUE, full.names = TRUE)

bianca_cluster_info(pipeline1, threshold = 0.8)
bianca_cluster_info(pipeline2, threshold = 0.8)

```

# Volume extraction

```{r}
pipeline1txt <- list.files("/mnt/Vierer/BIDS/derivatives_temp/FSL/fsl_bianca_pipeline/model_121_deface_anat/", ".txt", recursive = TRUE, full.names = TRUE)
pipeline2txt <- list.files("/mnt/Vierer/BIDS/derivatives_temp/FSL/fsl_bianca_pipeline/model_121_deface_bc_anat/", ".txt", recursive = TRUE, full.names = TRUE)


model121_deface_anat <- tibble(subject = str_extract(pipeline1txt, "sub-[:digit:]{5}"),
       session = str_extract(pipeline1txt, "ses-s[:digit:]{1}"),
       wmh_number1 = lapply(pipeline1txt, volume_extractor, "wmh_number") %>% unlist() %>% as.numeric(),
       wmh_volume1 = lapply(pipeline1txt, volume_extractor, "total_wmh_volume") %>% unlist() %>% as.numeric(),
       wmh_number2 = lapply(pipeline2txt, volume_extractor, "wmh_number") %>% unlist() %>% as.numeric(),
       wmh_volume2 = lapply(pipeline2txt, volume_extractor, "total_wmh_volume") %>% unlist() %>% as.numeric())


readr::write_csv(model121_deface_anat, path = "/home/niklas/Owncloud/wulms/BD_variablen/neuroimaging/bianca_pipelines2.csv")

```

```{r}
library(ggplot2)
model121_deface_anat %>%
  ggplot(aes(x=wmh_volume1, y = wmh_volume2)) +
  geom_point()

model121_deface_anat %>%
  ggplot(aes(x=wmh_number1, y = wmh_number2)) +
  geom_point()


```

```{r}
model121_deface_anat %>%
  ggplot(aes(x=wmh_volume1, y = wmh_number1)) +
  geom_point()

model121_deface_anat %>%
  ggplot(aes(x=wmh_volume2, y = wmh_number2)) +
  geom_point()
```

