---
title: "Preprocessing_QC"
author: "Niklas Wulms"
date: "10/16/2019"
output: html_document
---
```{r setup, include=FALSE}
library(stringr)
library(doParallel)
library(foreach)
library(tidyr)
library(dplyr)

source("../2-image_quality/qc_fsleyes.R")
source("../tools/path_to_folder.R")

knitr::opts_chunk$set(echo = TRUE)

working_dir <- "/media/niklas/spaceC/WML121_BIDS_2"

knitr::opts_knit$set(root.dir = working_dir)

setwd(working_dir)
```

# Parallel setup

```{r}

# Calculate the number of cores
no_cores <- detectCores() - 1

# Initiate cluster
cl <- makeCluster(no_cores, type="FORK", outfile = "")

registerDoParallel(cl)
getDoParWorkers()
```

# input images

```{r}
MD_native = list.files(working_dir, "temp-DTI_FA.nii.gz", recursive = T, full.names = F)
MD_native <- MD_native[str_detect(MD_native, "tbss/MD/") == 1]

psmd_files <- data.frame(
  # raw input and first preprocs
  FA_native = list.files(working_dir, "temp-DTI_FA_FA.nii.gz", recursive = T, full.names = F),
  MD_native = MD_native,
  FA_normalized = list.files(working_dir, "all_FA.nii.gz", recursive = T, full.names = F),
  MD_normalized = list.files(working_dir, "all_MD.nii.gz", recursive = T, full.names = F),
  
  stringsAsFactors = F
)

head(psmd_files)
```

```{r}
psmd_png <- data.frame(
  FA_native_axial = str_replace(psmd_files$FA_native, "base_protocol", "qualitycontrol/4-psmd_tbss/FA_native_axial") %>% 
    str_replace("dwi/psmdtemp/tbss/FA/temp-DTI_FA_FA.nii.gz", "FA_native.png") %>% str_replace("/ses-1/", "_ses-1_") %>% str_replace("/ses-3/", "_ses-3_"),
  MD_native_axial = str_replace(psmd_files$MD_native, "base_protocol", "qualitycontrol/4-psmd_tbss/MD_native_axial") %>% 
    str_replace("dwi/psmdtemp/tbss/MD/temp-DTI_FA.nii.gz", "MD_native.png") %>% str_replace("/ses-1/", "_ses-1_") %>% str_replace("/ses-3/", "_ses-3_"),
  FA_normalized_axial = str_replace(psmd_files$FA_normalized, "base_protocol", "qualitycontrol/4-psmd_tbss/FA_norm_axial") %>% 
    str_replace("dwi/psmdtemp/tbss/stats/all_FA.nii.gz", "FA_normalized.png") %>% str_replace("/ses-1/", "_ses-1_") %>% str_replace("/ses-3/", "_ses-3_"),
  MD_normalized_axial = str_replace(psmd_files$MD_normalized, "base_protocol", "qualitycontrol/4-psmd_tbss/MD_norm_axial") %>% 
    str_replace("dwi/psmdtemp/tbss/stats/all_MD.nii.gz", "MD_normalized.png") %>% str_replace("/ses-1/", "_ses-1_") %>% str_replace("/ses-3/", "_ses-3_"),  
  FA_native_sagittal = str_replace(psmd_files$FA_native, "base_protocol", "qualitycontrol/4-psmd_tbss/FA_native_sagittal") %>% 
    str_replace("dwi/psmdtemp/tbss/FA/temp-DTI_FA_FA.nii.gz", "FA_native.png") %>% str_replace("/ses-1/", "_ses-1_") %>% str_replace("/ses-3/", "_ses-3_"),
  MD_native_sagittal = str_replace(psmd_files$MD_native, "base_protocol", "qualitycontrol/4-psmd_tbss/MD_native_sagittal") %>% 
    str_replace("dwi/psmdtemp/tbss/MD/temp-DTI_FA.nii.gz", "MD_native.png") %>% str_replace("/ses-1/", "_ses-1_") %>% str_replace("/ses-3/", "_ses-3_"),
  FA_normalized_sagittal = str_replace(psmd_files$FA_normalized, "base_protocol", "qualitycontrol/4-psmd_tbss/FA_norm_sagittal") %>% 
    str_replace("dwi/psmdtemp/tbss/stats/all_FA.nii.gz", "FA_normalized.png") %>% str_replace("/ses-1/", "_ses-1_") %>% str_replace("/ses-3/", "_ses-3_"),
  MD_normalized_sagittal = str_replace(psmd_files$MD_normalized, "base_protocol", "qualitycontrol/4-psmd_tbss/MD_norm_sagittal") %>% 
    str_replace("dwi/psmdtemp/tbss/stats/all_MD.nii.gz", "MD_normalized.png") %>% str_replace("/ses-1/", "_ses-1_") %>% str_replace("/ses-3/", "_ses-3_"),
  FA_processing_low_res = str_replace(psmd_files$FA_native, "base_protocol", "qualitycontrol/4-psmd_tbss/FA") %>% 
    str_replace("dwi/psmdtemp/tbss/FA/temp-DTI_FA_FA.nii.gz", "low_res_FA.png") %>% str_replace("/ses-1/", "_ses-1_") %>% str_replace("/ses-3/", "_ses-3_"),
  MD_processing_low_res = str_replace(psmd_files$MD_native, "base_protocol", "qualitycontrol/4-psmd_tbss/MD") %>% 
    str_replace("dwi/psmdtemp/tbss/MD/temp-DTI_FA.nii.gz", "low_res_MD.png") %>% str_replace("/ses-1/", "_ses-1_") %>% str_replace("/ses-3/", "_ses-3_"),
  
  stringsAsFactors = FALSE
)

dir.create("qualitycontrol/4-psmd_tbss/FA_native_axial", recursive = TRUE)
dir.create("qualitycontrol/4-psmd_tbss/FA_native_sagittal", recursive = TRUE)
dir.create("qualitycontrol/4-psmd_tbss/MD_native_axial", recursive = TRUE)
dir.create("qualitycontrol/4-psmd_tbss/MD_native_sagittal", recursive = TRUE)
dir.create("qualitycontrol/4-psmd_tbss/FA_norm_axial", recursive = TRUE)
dir.create("qualitycontrol/4-psmd_tbss/FA_norm_sagittal", recursive = TRUE)
dir.create("qualitycontrol/4-psmd_tbss/MD_norm_axial", recursive = TRUE)
dir.create("qualitycontrol/4-psmd_tbss/MD_norm_sagittal", recursive = TRUE)

dir.create("qualitycontrol/4-psmd_tbss/FA", recursive = TRUE)
dir.create("qualitycontrol/4-psmd_tbss/MD", recursive = TRUE)


```


```{r}


qc_fsleyes_dwi_nativ(psmd_files$FA_native, psmd_png$FA_native_axial, psmd_png$FA_native_sagittal)
qc_fsleyes_dwi_nativ(psmd_files$MD_native, psmd_png$MD_native_axial, psmd_png$MD_native_sagittal)

qc_fsleyes_dwi_norm(psmd_files$FA_normalized, psmd_png$FA_normalized_axial, psmd_png$FA_normalized_sagittal)
qc_fsleyes_dwi_norm(psmd_files$MD_normalized, psmd_png$MD_normalized_axial, psmd_png$MD_normalized_sagittal)
```

```{r}
collage_four(psmd_png$FA_native_axial, psmd_png$FA_normalized_axial, psmd_png$FA_native_sagittal, psmd_png$FA_normalized_sagittal, psmd_png$FA_processing_low_res)
```

