---
title: "PSMD"
author: "Niklas Wulms"
date: "2/27/2020"
output: html_document
---


```{r setup, include=FALSE}
library(dplyr)
library(tidyr)
library(stringr)
library(logger)
library(doParallel)
library(foreach)

log_threshold(DEBUG)

knitr::opts_chunk$set(echo = TRUE)

bids_source_dir <- "/mnt/Storage1/bidirect2bids/bids/sourcedata/"

bids_derivatives_dir_psmd <- "/mnt/Vierer/BIDS/derivatives_temp/FSL/PSMD"

bids_derivatives_dir_msmd <- "/mnt/Vierer/BIDS/derivatives_temp/FSL/MSMD"

# PSMD files
psmd_script <- "/home/niklas/Programme/psmd_new/psmd.sh"
skeleton_mask <- "/home/niklas/Programme/psmd_new/skeleton_mask_2019.nii.gz"

source("../functions/general.R")
source("../bids/bids_functions.R")


```

```{r}
copy_BIDS(BIDS_sourcedata_dir = bids_source_dir, 
          BIDS_tag = "dwi.(nii|bvec|bval)", 
          seq_n = 1, 
          BIDS_derivatives_temp_dir = bids_derivatives_dir_psmd,
          gunzip = FALSE)
```

# Input files

```{r}
dwi <- list.files(bids_derivatives_dir_psmd,
                               recursive = TRUE,
                               pattern = "dwi.nii",
                               all.files = TRUE,
                               full.names = TRUE)
```

# Start parallelization (used cores: max-2)

```{r}

```


```{r}
psmd <- function(dwi_input) {
  # Starting parallel cluster
  # Calculate the number of cores
  no_cores <- detectCores() - 2
  # Initiate cluster
  cl <- makeCluster(no_cores, type="FORK", outfile = "")
  getDoParWorkers()
  registerDoParallel(cl)
  
  # Input filenames
  bval = str_replace(dwi_input, ".nii.gz", ".bval")
  bvec = str_replace(dwi_input, ".nii.gz", ".bvec")
  # Output file and foldernames
  psmd_txt <- str_replace(dwi_input, "dwi.nii.gz", "psmd.txt")  
  folder <- sub("[/][^/]+$", "", dwi_input)

  foreach (i = 1:length(dwi_input)) %dopar% {
    # Shell command
    command <- paste0("bash ", psmd_script, " -t ", 
                      " -d ", dwi_input[i], 
                      " -b ", bval[i],
                      " -r ", bvec[i],
                      " -s ", skeleton_mask,
                      " > ", psmd_txt[i])
    print(command)
    
    if(!file.exists(psmd_txt[i])){
      setwd(folder[i])
      system(command)
    }
  }
  stopCluster(cl)
}

```

# Run function

```{r}
psmd(dwi)
```

# Read value from txt values

```{r}
psmd_extraction <- function(txt_file){
  psmd_value = readr::read_lines(txt_file, skip = 10)[1] %>% 
    str_extract("[:digit:]{1}.[:digit:]+$") %>% 
    as.numeric()
  return(psmd_value)
}
```

# Write to csv file

```{r}
psmd_txt <- tibble(txt = list.files(bids_derivatives_dir_psmd,
                               recursive = TRUE,
                               pattern = "psmd.txt",
                               all.files = TRUE,
                               full.names = TRUE),
                   subject = str_extract(txt, "sub-[:digit:]{5}"),
                   session = str_extract(txt, "ses-s[:digit:]{1}")
                   ) %>%
                   mutate(psmd_string = unlist(lapply(txt, psmd_extraction)))

readr::write_excel_csv(psmd_txt, path = paste0(bids_derivatives_dir_psmd, "/psmd.csv"))
```



# MSMD (same structure as PSMD, some small changes to extract MSMD value)

```{r}
copy_BIDS(BIDS_sourcedata_dir = bids_source_dir, 
          BIDS_tag = "dwi.(nii|bvec|bval)", 
          seq_n = 3, 
          BIDS_derivatives_temp_dir = bids_derivatives_dir_msmd,
          gunzip = FALSE)
```

# Input files

```{r}
dwi <- list.files(bids_derivatives_dir_msmd,
                               recursive = TRUE,
                               pattern = "dwi.nii",
                               all.files = TRUE,
                               full.names = TRUE)
```

# Function definition

```{r}
msmd <- function(dwi_input) {
  # Parallel cluster start
  # Calculate the number of cores
  no_cores <- detectCores() - 2
  # Initiate cluster
  cl <- makeCluster(no_cores, type="FORK", outfile = "")
  getDoParWorkers()
  registerDoParallel(cl)
  
  # File namings
  bval = str_replace(dwi_input, ".nii.gz", ".bval")
  bvec = str_replace(dwi_input, ".nii.gz", ".bvec")
  # Output file and folders
  msmd_txt <- str_replace(dwi_input, "dwi.nii.gz", "msmd.txt")  
  folder <- sub("[/][^/]+$", "", dwi_input)

  foreach (i = 1:length(dwi_input)) %dopar% {
    # Shell command as string
    command <- paste0("bash ", psmd_script, " -o -t ", 
                      " -d ", dwi_input[i], 
                      " -b ", bval[i],
                      " -r ", bvec[i],
                      " -s ", skeleton_mask,
                      " > ", msmd_txt[i])
    print(command)
    
    if(!file.exists(msmd_txt[i])){
      setwd(folder[i])
      system(command)
    }
  }
  stopCluster(cl)
}

```

# Run function

```{r}
msmd(dwi)
```

# Write to csv file

```{r}
msmd_txt <- tibble(txt = list.files(bids_derivatives_dir_msmd,
                               recursive = TRUE,
                               pattern = "msmd.txt",
                               all.files = TRUE,
                               full.names = TRUE),
                   subject = str_extract(txt, "sub-[:digit:]{5}"),
                   session = str_extract(txt, "ses-s[:digit:]{1}")
                   ) %>%
                   mutate(msmd_string = unlist(lapply(txt, psmd_extraction)))

readr::write_excel_csv(msmd_txt, path = paste0(bids_derivatives_dir_msmd, "/msmd.csv"))

```
