---
title: "mriqc"
author: "Niklas Wulms"
date: "5/11/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)

path_to_folder <- function(list_of_files) {
  paths_folder <- sub("[/][^/]+$", "", list_of_files)
  paths_folder <- unique(paths_folder)
  paths_folder <- paths_folder[!dir.exists(paths_folder)]
  lapply(paths_folder,
         dir.create,
         recursive = TRUE,
         showWarnings = FALSE)
}
```
# MRIQC pipeline

## folders
```{r}
input_BIDS <- "/mnt/Storage1/bidirect_projektbox/BiDirect_Neuroimaging/Bidirect_BIDS/bids/sourcedata"
output_MRIQC <- "/mnt/Storage1/bidirect_processing/mriqc/out"
# here are the files copied and removed.
temp_batch_MRIQC <- "/mnt/Storage1/bidirect_processing/mriqc/temp"

```


```{r}
input_df <- tibble(path = list.files(input_BIDS, full.names = TRUE, recursive = TRUE) %>% str_subset("json|nii"),
       sub = str_extract(path, "sub-[:digit:]{5}"),
       session = str_extract(path, "ses-s[:digit:]{1}"),
       sub_session = str_extract(path, "sub-[:digit:]{5}_ses-s[:digit:]{1}"))

json_df <- input_df %>%
  filter(is.na(sub)) %>%
  mutate(path_output = str_replace(path, input_BIDS, temp_batch_MRIQC))

input_df <- input_df %>%
  filter(!is.na(sub))
```


```{r}
output_df <- tibble(path = list.files(output_MRIQC, full.names = TRUE, recursive = TRUE) %>% str_subset("html"),
       sub = str_extract(path, "sub-[:digit:]{5}"),
       session = str_extract(path, "ses-s[:digit:]{1}"),
       sub_session = str_extract(path, "sub-[:digit:]{5}_ses-s[:digit:]{1}"))

unprocessed_df <- anti_join(input_df, output_df, by = c("sub", "session", "sub_session")) %>%
  mutate(path_output = str_replace(path, input_BIDS, temp_batch_MRIQC))
```

# Preparation of temp folder


```{r}
subjects <- unique(unprocessed_df$sub_session)

# subjects <- subjects[1:5]

# remove all folders
list.dirs(temp_batch_MRIQC, full.names = T, recursive = F) %>% unlink(., recursive = TRUE)
file.copy(json_df$path, json_df$path_output)
```


```{r}
# loop containing all the action
for(i in 1:length(subjects)){
  print(paste("Processing: ", subjects[i]))
  
  subject <- str_extract(subjects[i], "sub-[:digit:]{5}")
  final_df <- unprocessed_df %>%
  filter(sub_session == subjects[i])
  
  # step 1: final_df to temp_batch folder
  # create folders
  path_to_folder(final_df$path_output)
  # copy
  file.copy(final_df$path, final_df$path_output)
  
  #create docker command
  docker_string = paste0("docker run --rm --tmpfs /run --tmpfs /tmp -v ", # --read-only 
                         temp_batch_MRIQC, ":/data:ro -v ",
                         output_MRIQC, ":/out poldracklab/mriqc:0.16.1 /data /out ",
                         "participant --participant_label ", subject, 
                         " --no-sub -v") # verbose -v or -vvv (debug)
  print(docker_string)
  
  system(docker_string)
  
  # run docker command on folder participant level
  
  if(i %% 2 == 0){cat("\014")}
  
  # remove all folders
  list.dirs(temp_batch_MRIQC, full.names = T, recursive = F) %>% unlink(., recursive = TRUE)
}


```



