---
title: "Freesurfer Extractor"
author: "Niklas Wulms"
date: "9/2/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)

source("freesurfer_extraction_functions.R")

working_dir = "/home/niklas/Owncloud/wulms/BD_variablen/neuroimaging/anat/freesurfer_stats_files/"

output_data = "/home/niklas/Owncloud/wulms/BD_variablen/neuroimaging/anat/freesurfer_stats_merged/"
```

```{r}
freesurfer <- tibble(files = list.files(working_dir, "stats$", recursive = TRUE, full.names = TRUE),
                     subject = str_extract(files, "sub-[:digit:]{5}"),
                     session = str_extract(files, "ses-s[:digit:]{1}"),
                     type = str_extract(files, "(?<=stats/)[:graph:]+$")) %>% 
  filter(str_detect(files, "/stats/")) %>%
  mutate(txt = purrr::map(files, readr::read_lines),
         length = purrr::map(txt, length)) %>%
  arrange(type)

freesurfer_split <- freesurfer  %>%
  group_split(type)

                           
freesurfer_keys <- freesurfer %>% group_keys(type)

freesurfer_wide <- freesurfer %>% select(-length, -files) %>% pivot_wider(names_from = type, values_from = txt)


```


# Global: aseg, brainvol, wmparc

- brainvol is fully implemented in aseg.stats!

```{r}
###
freesurfer_global <- freesurfer %>% 
  filter(str_detect(type, "aseg|wmparc")) %>%
  mutate(hemisphere = "global")

freesurfer_global_tables <- freesurfer_global %>%
  mutate(table_measure = lapply(freesurfer_global$txt, str_subset, "Measure"),
         table_roi = lapply(freesurfer_global$txt, str_subset, "ColHeaders|^( |  )[:digit:]{1}"))
```


# Hemisphere: all with rh or lh


```{r}
###
freesurfer_hemi <- freesurfer %>% 
  filter(str_detect(type, "^(l|r)h.")) %>%
  filter(str_detect(type, "pct|curv", negate = TRUE)) %>%
  mutate(hemisphere = str_extract(type, "^(l|r)") %>% str_replace("l", "left") %>% str_replace("r", "right"))

freesurfer_hemi_tables <- freesurfer_hemi %>%
  mutate(table_measure = lapply(freesurfer_hemi$txt, str_subset, "Measure"),
         table_roi = lapply(freesurfer_hemi$txt, str_subset, "ColHeaders|^(| )[:alpha:]{1}"))
```

## irrelevant until now

- w-g.ct.stats
- curv.stats

```{r}
### pct table
freesurfer_hemi_pct <- freesurfer %>% 
  filter(str_detect(type, "pct"))

freesurfer_hemi_pct_tables <- freesurfer_hemi_pct %>%
  mutate(hemisphere = str_extract(type, "^(l|r)") %>% str_replace("l", "left") %>% str_replace("r", "right"),
         table_measure = lapply(freesurfer_hemi_pct$txt, str_subset, "Measure"),
         table_roi = lapply(freesurfer_hemi_pct$txt, str_subset, "ColHeaders|^( |  )[:digit:]{1}"))

### curvature table ???
freesurfer_hemi_curv <- freesurfer %>% 
  filter(str_detect(type, "curv"))
```


## measure extraction


```{r}
# writes csv files of measure
extract_table_measures(freesurfer_global_tables)
extract_table_measures(freesurfer_hemi_tables)
```



```{r}
# writes csv files of ROI
extract_table_roi(freesurfer_global_tables, extract_type = "global")
extract_table_roi(freesurfer_hemi_tables, extract_type = "thickness")
```


# find all csv files

```{r}
metainfo_csv <- tibble(csv_name = list.files(working_dir, pattern = ".csv", recursive = TRUE, full.names = TRUE),
       type = str_extract(csv_name, "stats_(measure|roi)"),
       sub = str_extract(csv_name, "sub-[:digit:]{5}"),
       session = str_extract(csv_name, "ses-s[:digit:]{1}"),
       table = str_extract(csv_name, "(?<=stats/)[:graph:]+$")) 


merge_table_information(metainfo_csv)
```



```{r}
csv_measure_files_to_merge <- list.files(output_data, pattern = "measure.csv", recursive = FALSE, full.names = TRUE)
csv_roi_files_to_merge <- list.files(output_data, pattern = "roi.csv", recursive = FALSE, full.names = TRUE)


merged_measure_df <- merge_csv_files(csv_measure_files_to_merge)
merged_roi_df <- merge_csv_files(csv_roi_files_to_merge)
```


```{r}
new_names <- colnames(merged_measure_df) %>% 
  str_replace(".(?=stats)", "_-") %>%
  str_replace("\\(", "in ") %>% 
  str_replace("[:space:]", "_-_") %>% 
  str_replace("[:space:]", "_-_") %>% 
  str_replace_all("[[:punct:]]", "_") %>% 
  str_replace_all("__", "_") %>% 
  str_remove_all("\\^|_$")

str_split(new_names, "__", n = 4, simplify = TRUE)

colnames(merged_measure_df) <- new_names

##################
new_names <- colnames(merged_roi_df) %>% 
#  str_replace("\\(", "in ") %>% 
  str_replace_all("-", "") %>%
  str_replace("_(?=[:alnum:]*$)", "_-_") %>% 
#  str_replace("[:space:]", "_-_") %>% 
#  str_replace("[:space:]", "_-_") %>% 
  str_replace_all("stats_", "stats_-_") %>%
  str_replace_all("\\.", "_") %>% 
  str_replace_all("_-_", "__") %>%
  str_replace("Volume__mm3", "_Volume_mm3")

str_split(new_names, "__", n = 3, simplify = TRUE)

colnames(merged_roi_df) <- new_names

####################
write_csv(merged_measure_df, path = paste0(output_data, "freesurfer_merged/freesurfer_measures.csv"))
write_csv(merged_roi_df, path = paste0(output_data, "freesurfer_merged/freesurfer_roi.csv"))
```


```{r}
library(dataMaid)
makeDataReport(merged_measure_df, replace = TRUE)
makeDataReport(merged_roi_df, replace = TRUE)
```



```{r}
measure_df_long <- merged_measure_df %>% 
  pivot_longer(cols = contains("stats")) %>%
  separate(name, sep = "__", into = c("file", "region", "metric")) %>%
  separate(file, sep = "_stats_", into = c("file", "ROI")) %>% 
  mutate(hemisphere = str_extract(ROI, "lh|rh") %>% str_replace("lh", "Left") %>% str_replace("rh", "Right"),
         hemisphere2 = str_extract(file, "lh|rh") %>% str_replace("lh", "Left") %>% str_replace("rh", "Right"),
         hemisphere3 = paste0(hemisphere, hemisphere2) %>% str_remove_all("NA"),
         file_clean = str_remove(file, "(lh|rh)_"),
         roi_clean = str_remove(ROI, "lh|rh"),
         region = str_remove(region, "lh|rh")) %>%
  select(-hemisphere, -hemisphere2, -file, -ROI) %>%
  rename(hemisphere = hemisphere3)

roi_df_long <- merged_roi_df %>% 
  pivot_longer(cols = contains("stats")) %>%
  separate(name, sep = "__", into = c("file", "region", "metric")) %>%
  mutate(file = str_remove(file, "_stats"),
         hemisphere = str_extract(region, "Left|Right|(lh|rh)(?!inal)") %>% str_replace("lh", "Left") %>% str_replace("rh", "Right"),
         hemisphere2 = str_extract(file, "lh|rh") %>% str_replace("lh", "Left") %>% str_replace("rh", "Right"),
         hemisphere3 = paste0(hemisphere, hemisphere2) %>% str_remove_all("NA"),
         region_clean = str_remove(region, "Left|Right|wmlh|wmrh"),
         file_clean = str_remove(file, "(lh|rh)_")) %>%
  select(-hemisphere, -hemisphere2, -file, - region)


```


```{r}
library(rpivotTable)

test <- measure_df_long %>%
  filter(subject == "sub-30001") %>%
  filter(session == "ses-s0")


rpivotTable(test,
            cols = c("file_clean", "hemisphere"),
            rows = c("region", "metric", "session", "value"))



test1 <- roi_df_long %>%
  filter(subject == "sub-30001") %>%
  filter(session == "ses-s0") %>%
  filter(str_detect(file_clean, "aseg|wmparc", negate = TRUE))

test2 <- roi_df_long %>%
  filter(subject == "sub-30001") %>%
  filter(session == "ses-s0") %>%
  filter(str_detect(file_clean, "aseg|wmparc"))



## variable

rpivotTable(test2,
            cols = c("file_clean"),
            rows = c("metric", "region_clean", "session", "hemisphere3", "value"))
```

```{r}
library(rpivotTable)
library(htmlwidgets)
    
# savedPivot <- "iris.html"
# rpivotTable(iris)   
# saveWidget(rpivotTable(iris), savedPivot, savedPivot)
# saveWidget(rpivotTable(iris),file.path(normalizePath(dirname(savedPivot)),basename(savedPivot)))


##
savedPivot <- "freesurfer_wholebrain.html"
rpivotTable(test,
            cols = c("file_clean", "hemisphere"),
            rows = c("region", "metric"))   
saveWidget(rpivotTable(test,
            cols = c("file_clean", "hemisphere"),
            rows = c("region", "metric")),
           file.path(normalizePath(dirname(savedPivot)),
                     basename(savedPivot)))
##
savedPivot <- "freesurfer_aseg_wmparc.html"
rpivotTable(test1,
            cols = c("metric", "hemisphere3"),
            rows = c("region_clean", "file_clean"))   
saveWidget(rpivotTable(test1,
            cols = c("metric", "hemisphere3"),
            rows = c("region_clean", "file_clean")),file.path(normalizePath(dirname(savedPivot)),basename(savedPivot)))
##
savedPivot <- "freesurfer_roi.html"
rpivotTable(test2,
            cols = c("metric", "hemisphere3"),
            rows = c("region_clean", "file_clean"))   
saveWidget(rpivotTable(test2,
            cols = c("metric", "hemisphere3"),
            rows = c("region_clean", "file_clean")),file.path(normalizePath(dirname(savedPivot)),basename(savedPivot)))
```


```{r}
rpivotTable(measure_df_long,
            cols = c("file_clean", "hemisphere"),
            rows = c("region", "metric"))

rpivotTable(roi_df_long,
            cols = c("metric", "hemisphere3"),
            rows = c("region_clean", "file_clean"))

rpivotTable(roi_df_long)
```


# remove duplicate rows
```{r}
library(digest)
merged_measure_df_duplicates_removed <- merged_measure_df[!duplicated(lapply(merged_measure_df, digest))]
merged_roi_df_duplicates_removed <- merged_roi_df[!duplicated(lapply(merged_roi_df, digest))]
```

```{r}
setdiff(names(merged_measure_df), names(merged_measure_df_duplicates_removed))
setdiff(names(merged_roi_df), names(merged_roi_df_duplicates_removed))

```








